# 데이터 전처리

### 1. 레이블 인코딩

In [1]:
from sklearn.preprocessing import LabelEncoder

In [2]:
items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

In [3]:
# 레이블 인코더 객체 생성
le = LabelEncoder()

In [4]:
# 학습, 데이터를 훑어 봄
le.fit(items)

LabelEncoder()

In [5]:
# 인코딩 실행
labels = le.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [6]:
# 실전에서는
le2 = LabelEncoder()
labels = le2.fit_transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [7]:
# 고수들은
    # 변수를 쓰지 않으려면, 객체를 생성한 다음에 메소드를 적용하는 식으로 진행할 수 있다. 
    #   - 메소드 체이닝:
labels = LabelEncoder().fit_transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [11]:
# 변수를 쓰지 않으려면, 객체를 생성한 다음에 메소드를 적용하는 식으로 진행할 수 있다. 
# method chaining 1 : 메소드를 연결해서 값을 출력함
s = '  A quick brown fox  '
s.lower().strip().split() 


['a', 'quick', 'brown', 'fox']

In [12]:
# method chaining 2
s = '  A quick brown fox  '
s.lower().lstrip().rstrip().replace('a', 'the').replace('fox','wolf').split() 


['the', 'quick', 'brown', 'wolf']

In [13]:
# inverse_transform은 label encoder에서 사용할 수 없음
le.inverse_transform([4,5,2,3,0,1])

array(['전자렌지', '컴퓨터', '믹서', '선풍기', 'TV', '냉장고'], dtype='<U4')

### 2. One-hot encoding
    - 사이킷런에서 잘 사용하지 않는다. but, 신경망, 딥러닝에서는 사용하므로 알아두는 것이 좋다.
    - 6 종류가 있다면, 사이즈가 6인 벡터를 만든다
    - 1개만 1로 남겨두고, 나머지는 0으로 설정한다.


In [14]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [15]:
oh_labels = ohe.fit_transform(labels.reshape(-1,1))
oh_labels

<8x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [17]:
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

- reshape 공부

In [22]:
import numpy as np
a = np.arange(24).reshape(4,6)
a # a의 element 개수는 24개

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [23]:
a.reshape(2,-1) # 행이 2개 열이 12개

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [24]:
a.reshape(2, -1, 4) # 3차원 배열이 2개, 행은 3개, 열은 4개

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### 3. 표준화 (Standardization) - 표준정규분포 변환

In [25]:
from sklearn.datasets import load_iris
iris = load_iris()

In [26]:
import pandas as pd
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [28]:
from sklearn.preprocessing import StandardScaler

iris_std = StandardScaler().fit_transform(iris.data)

In [30]:
df2 = pd.DataFrame(iris_std, columns=iris.feature_names)
df2.describe()
# 평균이 0이고 표준편차가 1인 정규분포 생성 
#   N(1,0)

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count       1.500000e+02      1.500000e+02       1.500000e+02   
mean       -1.690315e-15     -1.842970e-15      -1.698641e-15   
std         1.003350e+00      1.003350e+00       1.003350e+00   
min        -1.870024e+00     -2.433947e+00      -1.567576e+00   
25%        -9.006812e-01     -5.923730e-01      -1.226552e+00   
50%        -5.250608e-02     -1.319795e-01       3.364776e-01   
75%         6.745011e-01      5.586108e-01       7.627583e-01   
max         2.492019e+00      3.090775e+00       1.785832e+00   

       petal width (cm)  
count      1.500000e+02  
mean      -1.409243e-15  
std        1.003350e+00  
min       -1.447076e+00  
25%       -1.183812e+00  
50%        1.325097e-01  
75%        7.906707e-01  
max        1.712096e+00

- Logistic Regression으로 분류


In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, stratify=iris.target, test_size=0.2, random_state=2021
)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [36]:
from sklearn.linear_model import LogisticRegression
lrc = LogisticRegression()
lrc.fit(X_train, y_train)
# Increase the number of iterations (max_iter) or scale the data as shown in => scaling이 필요하다는 의미

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
# 표준정규분포로 변환된 데이터로 학습하면 에러가 발생하지 않음

X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, stratify=iris.target, test_size=0.2, random_state=2021
)

lrc = LogisticRegression()
lrc.fit(X_train, y_train)