# 평가

### 1. MNIST 손글씨 - Is it seven?

In [1]:
import numpy as np 
import pandas as pd
from sklearn.datasets import load_digits

In [2]:
digits = load_digits()
digits.data.shape

(1797, 64)

In [3]:
digits.data[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [4]:
# 문제가 'Is it seven?' 이므로 타겟 값이 7이면 1, 나머지는 0
X = digits.data
y = (digits.target == 7).astype(int)
X.shape, y.shape 

((1797, 64), (1797,))

In [5]:
y[:5]   # target == 7 = True = 1 , target != 7 = False = 0

array([0, 0, 0, 0, 0])

In [7]:
np.unique(y, return_counts=True)

(array([0, 1]), array([1618,  179], dtype=int64))

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, stratify=y, random_state=2021
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1347, 64), (450, 64), (1347,), (450,))

- SVM으로 학습 및 평가

In [10]:
from sklearn.svm import SVC
svc = SVC(random_state=2021)
svc.fit(X_train, y_train)
pred_sv = svc.predict(X_test)
svc.score(X_test, y_test)

0.9977777777777778

- 엉터리 분류기로 학습 예측 평가

In [11]:
from sklearn.base import BaseEstimator

class MyClassifier(BaseEstimator):
    def fit(self, X, y):
        pass
    def predict(self,X):            # 무조건 0을 반환
        return np.zeros(X.shape[0])


In [12]:
my_clf = MyClassifier()
my_clf.fit(X_train, y_train)
pred_my = my_clf.predict(X_test)

In [13]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, pred_my)

0.9

In [14]:
# confusion matrix 참고 : https://leedakyeong.tistory.com/entry/%EB%B6%84%EB%A5%98-%EB%AA%A8%EB%8D%B8-%EC%84%B1%EB%8A%A5-%ED%8F%89%EA%B0%80-%EC%A7%80%ED%91%9C-Confusion-Matrix%EB%9E%80-%EC%A0%95%ED%99%95%EB%8F%84Accuracy-%EC%A0%95%EB%B0%80%EB%8F%84Precision-%EC%9E%AC%ED%98%84%EB%8F%84Recall-F1-Score
from sklearn.metrics import confusion_matrix, precision_score, recall_score
confusion_matrix(y_test, pred_sv)

array([[404,   1],
       [  0,  45]], dtype=int64)

In [15]:
precision_score(y_test, pred_sv), recall_score(y_test, pred_sv) # precision_score: 정밀도, recall_score: 재현율 

(0.9782608695652174, 1.0)

In [16]:
confusion_matrix(y_test, pred_my)

array([[405,   0],
       [ 45,   0]], dtype=int64)

In [17]:
precision_score(y_test, pred_my), recall_score(y_test, pred_my)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(0.0, 0.0)