# Wine 데이터 분류

#### 1) 데이터 전처리


In [1]:
from sklearn.datasets import load_wine
wine = load_wine()

In [3]:
import pandas as pd
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df['target'] = wine.target
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0

In [5]:
df.shape # 행의 개수는 178개, feature의 개수는 14개

(178, 14)

In [7]:
df.target.value_counts() # 데이터 분포가 일정하지 않음을 확인

1    71
0    59
2    48
Name: target, dtype: int64

In [9]:
wine.target_names # 분류하고자 하는 데이터의 기준은 target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

#### 2) 훈련 / 테스트 데이터셋 분리

In [12]:
wine.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [14]:
# Feature data - x data
wine.data[:5]

array([[1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
        3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, 1.120e+01, 1.000e+02, 2.650e+00,
        2.760e+00, 2.600e-01, 1.280e+00, 4.380e+00, 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, 1.860e+01, 1.010e+02, 2.800e+00,
        3.240e+00, 3.000e-01, 2.810e+00, 5.680e+00, 1.030e+00, 3.170e+00,
        1.185e+03],
       [1.437e+01, 1.950e+00, 2.500e+00, 1.680e+01, 1.130e+02, 3.850e+00,
        3.490e+00, 2.400e-01, 2.180e+00, 7.800e+00, 8.600e-01, 3.450e+00,
        1.480e+03],
       [1.324e+01, 2.590e+00, 2.870e+00, 2.100e+01, 1.180e+02, 2.800e+00,
        2.690e+00, 3.900e-01, 1.820e+00, 4.320e+00, 1.040e+00, 2.930e+00,
        7.350e+02]])

In [16]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [17]:
# Target data - y
wine.target[:5]

array([0, 0, 0, 0, 0])

In [18]:
import numpy as np
np.unique(wine.target, return_counts=True)
# 자료 불균형

(array([0, 1, 2]), array([59, 71, 48], dtype=int64))

In [20]:
wine.target_names
# class_0 : 59, class_1 : 71, class_2 : 48

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [21]:
print(wine.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [22]:
df.groupby('target').describe()

alcohol                                                             \
         count       mean       std    min     25%     50%     75%    max   
target                                                                      
0         59.0  13.744746  0.462125  12.85  13.400  13.750  14.100  14.83   
1         71.0  12.278732  0.537964  11.03  11.915  12.290  12.515  13.86   
2         48.0  13.153750  0.530241  12.20  12.805  13.165  13.505  14.34   

       malic_acid            ... od280/od315_of_diluted_wines       proline  \
            count      mean  ...                          75%   max   count   
target                       ...                                              
0            59.0  2.010678  ...                         3.42  4.00    59.0   
1            71.0  1.932676  ...                         3.16  3.69    71.0   
2            48.0  3.333750  ...                         1.82  2.47    48.0   

                                                                       
               mean         std    min    25%     50%     75%     max  
target                                                                 
0       1115.711864  221.520767  680.0  987.5  1095.0  1280.0  1680.0  
1        519.507042  157.211220  278.0  406.5   495.0   625.0   985.0  
2        629.895833  115.097043  415.0  545.0   627.5   695.0   880.0  

[3 rows x 104 columns]

In [23]:
df.groupby('target').agg(['mean', 'std'])

alcohol           malic_acid                 ash            \
             mean       std       mean       std      mean       std   
target                                                                 
0       13.744746  0.462125   2.010678  0.688549  2.455593  0.227166   
1       12.278732  0.537964   1.932676  1.015569  2.244789  0.315467   
2       13.153750  0.530241   3.333750  1.087906  2.437083  0.184690   

       alcalinity_of_ash             magnesium             ...  \
                    mean       std        mean        std  ...   
target                                                     ...   
0              17.037288  2.546322  106.338983  10.498949  ...   
1              20.238028  3.349770   94.549296  16.753497  ...   
2              21.416667  2.258161   99.312500  10.890473  ...   

       proanthocyanins           color_intensity                 hue  \
                  mean       std            mean       std      mean   
target                                                                 
0             1.899322  0.412109        5.528305  1.238573  1.062034   
1             1.630282  0.602068        3.086620  0.924929  1.056282   
2             1.153542  0.408836        7.396250  2.310942  0.682708   

                 od280/od315_of_diluted_wines                proline  \
             std                         mean       std         mean   
target                                                                 
0       0.116483                     3.157797  0.357077  1115.711864   
1       0.202937                     2.785352  0.496573   519.507042   
2       0.114441                     1.683542  0.272111   629.895833   

                    
               std  
target              
0       221.520767  
1       157.211220  
2       115.097043  

[3 rows x 26 columns]

In [24]:
df.target.value_counts()

1    71
0    59
2    48
Name: target, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    wine.data, wine.target, test_size=0.2, random_state=2021

)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((142, 13), (36, 13), (142,), (36,))

In [28]:
np.unique(y_train, return_counts=True) # 자료 불균형

(array([0, 1, 2]), array([44, 55, 43], dtype=int64))

In [118]:
X_train, X_test, y_train, y_test = train_test_split(
    wine.data, wine.target, stratify=wine.target, test_size=0.5, random_state=2021
)
np.unique(y_train, return_counts=True)

(array([0, 1, 2]), array([29, 36, 24], dtype=int64))

#### 3) GridSearchCV를 통해서
- DecisionTreeClassifier 또는 SVC를 선택해서
- 어떤 parameter일 때 최선의 모델이 되는지 파악하고
- 그때의 성능을 파악함

In [119]:
from sklearn.tree import DecisionTreeClassifier

In [120]:
dtc = DecisionTreeClassifier(random_state=2021)

In [121]:
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': 2021,
 'splitter': 'best'}

In [122]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier(random_state=2021)

In [123]:
pred_dt = dtc.predict(X_test)

In [124]:
pred_dt

array([0, 2, 1, 0, 1, 1, 2, 1, 1, 1, 1, 0, 2, 1, 0, 2, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 2, 0, 1, 1, 0, 2, 2, 1, 1, 0, 2, 2, 2, 1, 0, 2, 1,
       0, 0, 0, 2, 0, 0, 1, 1, 1, 0, 1, 0, 2, 0, 1, 1, 1, 0, 1, 2, 2, 1,
       1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 0, 2, 2, 1, 0, 2, 1,
       2])

In [125]:
res = pd.DataFrame({'y':y_test, 'DT':pred_dt})
res.head()

y  DT
0  0   0
1  2   2
2  0   1
3  0   0
4  1   1

In [126]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, pred_dt)

print(f"정확도: {acc:.4f}")

정확도: 0.9438


In [127]:
dtc.score(X_test, y_test)

0.9438202247191011

--------------------

In [129]:
# 2) 훈련 / 데이터셋 분리
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    wine.data, wine.target, test_size=0.2, random_state=2021

)

In [130]:
import numpy as np
np.unique(y_train, return_counts=True)

(array([0, 1, 2]), array([44, 55, 43], dtype=int64))

In [131]:
# 참고 - warning은 출력되지 않게 하는 메소드
import warnings
warnings.filterwarnings('ignore')

정확도 --> 모델로 측정하는 것까지 하진 못함

-----------------
- Decision Tree

---------------
- Support Vector Machine